source 'https://github.com/CocoaPods/Specs.git'

workspace 'AnyWall'

pod 'Parse'
pod 'ParseFacebookUtils'
pod 'ParseUI'
pod 'Facebook-iOS-SDK'

pod "TestDevPod", :path => './TestDevPod'
pod "TestDevPod2", :path => './TestDevPod2'
pod "TestDevPod3", :path => '../TestDevPod3'
