source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

workspace 'AnyWall'

pod 'Parse'
pod 'ParseFacebookUtils'
pod 'ParseUI'
pod 'Facebook-iOS-SDK'

pod "TestDevPod", :path => './TestDevPod'
